services:
  - type: web
    name: walletsecure-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: DEFAULT_SENDER_EMAIL
        sync: false
      - key: DEFAULT_SENDER_NAME
        sync: false
      - key: EMAIL_RATE_LIMIT
        value: "10"
      - key: MAX_CLIENTS_PER_USER
        value: "100"
      - key: ADMIN_USER_IDS
        value: ""
    autoDeploy: false